### ISSUE TITLE
Sim does not recognize

### ISSUE THREAD

**Issue by PantherSlaeyer** [BanditSim/L1011-100#1]
Hello,

I've downloaded your code and have extracted the folder to where it needs to be, in the community folder.  But, the sim doesn't recognize it at all.  I've deleted and copied several times and I thought I just might be missing it myself scrolling through the selected aircraft and I still cannot find it.

Any suggestions on how to get this recognized in the sim?

Thanks.

**Comment by aboodilatif** [comment]
Hi!

The folder ``banditsim-aircraft-lockheed-l1011`` located inside ``Packages/`` is the folder that you need to move to your ``Community`` folder.

a detailed walkthrough is available in the #faq channel on our Discord, the link to that is in the readme. If you're still having issues feel free to contact us on Discord.

Closing this.

**Comment by PantherSlaeyer** [comment]
That's exactly what I've done, no success.  What's the link to your discord?

**Comment by aboodilatif** [comment]
Hi!

https://discord.gg/NXeENnrRu9

will attempt to recreate your issue right now.
